### ISSUE TITLE
Gradescope infinte build

### ISSUE THREAD

**Issue by dklinenberg2020** [tbrown122387/Using-gradeR-for-the-Gradescope-Autograder#1]
Hello,

I'm working on making the `setup.sh` file for gradescope. I keep running into this issue where gradescope gets stuck in an infinite build. The timer stops and the program just gets stuck. I'm curious if others are running into this issue. I've attached the `setup.sh` file, since that's the file that actually builds the docker.
[setup.txt](https://github.com/tbrown122387/Using-gradeR-for-the-Gradescope-Autograder/files/6730629/setup.txt)

**Comment by tbrown122387** [comment]
@dklinenberg2020 what is the last bit of text that shows up in the output from grade scope? This sounds like it might be a thing on Gradescope's end, so you might want to send them an email (`help@gradescope.com` I believe). 

This issue has happened before, but nobody let's me know how they end up resolving it :(. Whenever it happens to me, I just re-upload the zip file, it rebuilds the docker image, and it usually goes away.
