### ISSUE TITLE
Fails to score code with any import of dplyr

### ISSUE THREAD

**Issue by ShanEllis** [tbrown122387/Using-gradeR-for-the-Gradescope-Autograder#2]
Hi! Thanks so much for sharing this. I've been digging into testing this out for use this Fall, and while it works great for certain cases, it fails (in a weird way), in others.

Specifically, if in the submitted .R file, a student imports `dplyr` (`library(dplyr)`), the autograder will return zero points for all tests. 

Notes: 
- `Rscript -e "install.packages('dplyr')" ` is included in `setup.sh`
- `dplyr` need not be used in the script to erroneously assign zero points to all tests; just importing it leads to `run_autograder.sh` returning zero points for all tests (regardless of what they are testing).
- If helpful for testing, the specific "student submitted code" could include:
```
library(dplyr)
mean_height <- mtcars %>% summarise(mean = mean(cyl)) %>% pull()
```
...and the test could be:

```
library(testthat)
test_that("Q8 (visible)", {
  expect_is(mean_height, "numeric")
  expect_equal(round(mean_height, 2), 174.36)
})
```

Happen to have any idea of why this could be the case? Figured if you could point me in the direction of the best place to look either here or in `gradeR`, I could work to come up with a possible solution! Figured I'd ask, as you know the code best at this point.

Shannon

**Comment by tbrown122387** [comment]
I forgot about this issue, but yes it's an unresolved issue with gradeR https://github.com/tbrown122387/gradeR/issues/10 I need to do some more testing, but it's a search path issue, i'm pretty sure. I forget all the particulars because I haven't looked at it in a while. I vaguely remember that you don't want to attach `library(testthat)` and `library(dplyr)` at the same time, but you can't not attach `library(testthat)` because that is called inside the body of its functions. 

What happens if you do something like add `dplyr::` to the beginning of all `dplyr` functions (e.g. `dplyr::summarise()`) so you don't have to `library(dplyr)` in the student submissions?

**Comment by tbrown122387** [comment]
Confirmed the short term workaround. Adding `dplyr::` to beginning of functon calls and not writing `library(dplyr)` passes tests.

Reproduce with 

`grade_one_submission.R`:

```
# load in the package
library(gradeR)

calcGradesForGradescope("stud_submission.R",       # each student's submission must be named this!
                        "test_file.R") # the file with all of the testthat tests 
  
```

`run_autograder`

```
#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/stud_submission.R /autograder/source/stud_submission.R

cd /autograder/source


Rscript grade_one_submission.r 
```


`setup.sh`

```
#!/usr/bin/env bash

# or you can do it the slow way...
apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
apt-get install -y r-base

# these lines install the packages that is needed both
# 1. the student code 
# 2. the autograding code
Rscript -e "install.packages('gradeR')" 
Rscript -e "install.packages('stringr')"
Rscript -e "install.packages('dplyr')"
```

and `test_file.R`

```
library(testthat)


test_that("a == 3 (visible)",{
  
  expect_true(
    a == 3
  )
})
```


`stud_submission.R` that works:
```
# instructor solutions
# do not share this with students

#library(dplyr)
df <- dplyr::tibble(
  x = sample(10, 100, rep = TRUE),
  y = sample(10, 100, rep = TRUE)
)
a <- 3
```

and `stud_submission.R` that doesn't work:
```
library(dplyr)
a <- 3
```

**Comment by tbrown122387** [comment]
Fixed it @ShanEllis . `callr::r()` needed the extra argument `package = TRUE`. `dplyr` was being installed on the Gradescope docker image, but `callr::r()` was not passing the package to the subprocess.

~~Just change `#Rscript -e "install.packages('gradeR')" ` to `Rscript -e "install.packages('devtools'); devtools::install_github('tbrown122387/gradeR')" ` in`setup.sh` to and you should be good to go. Alternatively, you can change nothing and wait for changes to take effect on CRAN.~~

Fixed version is now on CRAN. Just rebuild the docker image on Gradescope using the same files.

**Comment by tbrown122387** [comment]
CRAN asked for a resubmit might need to use GitHub version for a day or two

**Comment by ShanEllis** [comment]
This is the best Monday morning surprise (after I was away this past weekend)! Thanks for looking into this *and* fixing it so quickly. I'm going to play around for this (using GH version) today! :pray:

**Comment by tbrown122387** [comment]
@ShanEllis my pleasure. new code is now on CRAN.
