### ISSUE TITLE
Example submission in 'taylor' fails in gradescope

### ISSUE THREAD

**Issue by Ph-ADD** [tbrown122387/Using-gradeR-for-the-Gradescope-Autograder#4]
After uploading the files in ./autograding_code_and_data and ensuring the Gradescope can build the autograder, I checked the assignment files and got following error:

> The results uploaded to Gradescope were not formatted correctly. Please see
> http://gradescope-autograders.readthedocs.io/en/latest/specs/#output-format
> for more details.
> 
> Use the "Debug via SSH" button below to debug this issue.
> 
> 
> We did not receive any results for this submission.
> 
> The autograder produced the following output:
> 
> EEE
> [1] "error: source(source_file_path, rogueEnv)"
> NULL
> Error in testthat::test_file(test_file, reporter = lr, env = scriptResults) : 
>   object 'scriptResults' not found
> Calls: calcGradesForGradescope ... test_files -> test_files_serial -> test_files_setup_env -> %||%
> Execution halted
> 

A little investigation revealed it's the file in the 'taylor' folder. That assignment has an error for question 2 --- there is an extra colon in the creation of myVector.

> myVector <- 1::3

Not sure if the error is intentional or not, but it confused me for a bit when testing the repository.

**Comment by tbrown122387** [comment]
Thanks for spotting this. Yes, this was intentional, but I should at least mention that somewhere! I just fixed this in 93d29981d95d34619667326fba259c2d2724f042
